tests: get rid of dataclass that breaks on EPEL 9
tests/pytests/test_get_missing_licenses.py:28: in <module>
    class Call:
/usr/lib64/python3.9/dataclasses.py:1021: in dataclass
    return wrap(cls)
/usr/lib64/python3.9/dataclasses.py:1013: in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
/usr/lib64/python3.9/dataclasses.py:863: in _process_class
    cls_fields = [_get_field(cls, name, type)
/usr/lib64/python3.9/dataclasses.py:863: in <listcomp>
    cls_fields = [_get_field(cls, name, type)
/usr/lib64/python3.9/dataclasses.py:714: in _get_field
    and _is_type(f.type, cls, typing, typing.ClassVar,
/usr/lib64/python3.9/dataclasses.py:660: in _is_type
    ns = sys.modules.get(cls.__module__).__dict__
E   AttributeError: 'NoneType' object has no attribute '__dict__'